import { SearchResultsDataType } from '../resultDataType'

export const tests: SearchResultsDataType = [
  {
    id: 0,
    url: 'projets-entreprise',
    values: [
      'Diagnostic à 360° sur la transition écologique',
      'Sensibilisation des équipes',
      'Plan d’action économies d’énergie',
      "Plan d'action mobilité",
      'Plan d’action eau',
      'Plan d’action déchets &amp; pertes matière',
      'Réduction des emballages',
      'Bilan de gaz à effet de serre',
      'Économiseurs d’eau pour les sanitaires',
      "Économies d'eau en extérieur",
      'Ouvrants et ombrages',
      'Composteur',
      'Maîtrise des besoins de chauffage',
      'Audit énergétique',
      'Acquisition de vélos',
      'Isolation thermique',
      'Éco-conception d’un produit ou service',
      'Formation environnement',
      'Recrutement',
      'Tri des déchets',
      "Acquisition d'un véhicule propre",
      'Sèche-linge basse consommation',
      'Biodiversité',
      'Frigo basse consommation',
      'Eclairage LED',
      'Végétalisation',
      'Restauration durable',
      'Abris à vélos',
      'Récupérateur d’eau de pluie',
      'Plan d’adaptation au dérèglement climatique',
      'Pompe à chaleur',
      'Gestion des biodéchets',
      'Panneaux solaires',
      'Communication &amp; labélisation',
      'Chauffe-eau solaire',
      'Lutte contre le gaspillage alimentaire',
      'Serres agricoles',
      'Rétrofit électrique',
      'Chauffage au bois',
      'Plan de transition bas carbone',
      'Stratégie RSE',
      'Numérique responsable',
      'Projet de recherche',
      'Réseau de chaleur',
      'Chaleur de récupération',
      'Géothermie',
      'Energie hydraulique'
    ]
  },
  {
    id: 1,
    url: 'questionnaire/resultat?siret=83014132100034&effectif=TPE&locaux=proprietaire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=non&audit=non#questionnaire-resultat',
    values: [
      'Diagnostic à 360° sur la transition écologique',
      'Sensibilisation des équipes',
      "Plan d'action mobilité",
      'Plan d’action eau',
      'Plan d’action déchets &amp; pertes matière',
      'Réduction des emballages',
      'Bilan de gaz à effet de serre',
      'Économiseurs d’eau pour les sanitaires',
      "Économies d'eau en extérieur",
      'Ouvrants et ombrages',
      'Composteur',
      'Maîtrise des besoins de chauffage',
      'Audit énergétique',
      'Acquisition de vélos',
      'Isolation thermique',
      'Éco-conception d’un produit ou service',
      'Formation environnement',
      'Recrutement',
      'Tri des déchets',
      "Acquisition d'un véhicule propre",
      'Sèche-linge basse consommation',
      'Frigo basse consommation',
      'Restauration durable',
      'Abris à vélos',
      'Récupérateur d’eau de pluie',
      'Plan d’adaptation au dérèglement climatique',
      'Gestion des biodéchets',
      'Communication &amp; labélisation',
      'Lutte contre le gaspillage alimentaire',
      'Serres agricoles',
      'Rétrofit électrique',
      'Plan de transition bas carbone',
      'Stratégie RSE',
      'Numérique responsable',
      'Projet de recherche',
      'Diagnostic à 360° sur la transition écologique',
      'Sensibilisation des équipes',
      "Plan d'action mobilité",
      'Plan d’action eau',
      'Plan d’action déchets &amp; pertes matière',
      'Réduction des emballages',
      'Bilan de gaz à effet de serre',
      'Économiseurs d’eau pour les sanitaires',
      "Économies d'eau en extérieur",
      'Ouvrants et ombrages',
      'Composteur',
      'Maîtrise des besoins de chauffage',
      'Audit énergétique',
      'Acquisition de vélos',
      'Isolation thermique',
      'Éco-conception d’un produit ou service',
      'Formation environnement',
      'Recrutement',
      'Tri des déchets',
      "Acquisition d'un véhicule propre",
      'Sèche-linge basse consommation',
      'Frigo basse consommation',
      'Restauration durable',
      'Abris à vélos',
      'Récupérateur d’eau de pluie',
      'Plan d’adaptation au dérèglement climatique',
      'Gestion des biodéchets',
      'Communication &amp; labélisation',
      'Lutte contre le gaspillage alimentaire',
      'Serres agricoles',
      'Rétrofit électrique',
      'Plan de transition bas carbone',
      'Stratégie RSE',
      'Numérique responsable',
      'Projet de recherche'
    ]
  },
  {
    id: 2,
    url: 'questionnaire/resultat?siret=78893947800020&locaux=locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=oui&dechets=oui&gestion-eau=oui&energie=oui&audit=non#questionnaire-resultat',
    values: [
      'Diagnostic à 360° sur la transition écologique',
      'Sensibilisation des équipes',
      'Plan d’action économies d’énergie',
      "Plan d'action mobilité",
      'Plan d’action eau',
      'Plan d’action déchets &amp; pertes matière',
      'Réduction des emballages',
      'Bilan de gaz à effet de serre',
      'Économiseurs d’eau pour les sanitaires',
      "Économies d'eau en extérieur",
      'Composteur',
      'Maîtrise des besoins de chauffage',
      'Audit énergétique',
      'Acquisition de vélos',
      'Isolation thermique',
      'Éco-conception d’un produit ou service',
      'Formation environnement',
      'Recrutement',
      'Tri des déchets',
      "Acquisition d'un véhicule propre",
      'Sèche-linge basse consommation',
      'Frigo basse consommation',
      'Eclairage LED',
      'Restauration durable',
      'Abris à vélos',
      'Récupérateur d’eau de pluie',
      'Plan d’adaptation au dérèglement climatique',
      'Pompe à chaleur',
      'Gestion des biodéchets',
      'Panneaux solaires',
      'Communication &amp; labélisation',
      'Chauffe-eau solaire',
      'Lutte contre le gaspillage alimentaire',
      'Serres agricoles',
      'Rétrofit électrique',
      'Chauffage au bois',
      'Plan de transition bas carbone',
      'Stratégie RSE',
      'Numérique responsable',
      'Projet de recherche',
      'Réseau de chaleur',
      'Chaleur de récupération',
      'Géothermie',
      'Energie hydraulique',
      'Diagnostic à 360° sur la transition écologique',
      'Sensibilisation des équipes',
      'Plan d’action économies d’énergie',
      "Plan d'action mobilité",
      'Plan d’action eau',
      'Plan d’action déchets &amp; pertes matière',
      'Réduction des emballages',
      'Bilan de gaz à effet de serre',
      'Économiseurs d’eau pour les sanitaires',
      "Économies d'eau en extérieur",
      'Composteur',
      'Maîtrise des besoins de chauffage',
      'Audit énergétique',
      'Acquisition de vélos',
      'Isolation thermique',
      'Éco-conception d’un produit ou service',
      'Formation environnement',
      'Recrutement',
      'Tri des déchets',
      "Acquisition d'un véhicule propre",
      'Sèche-linge basse consommation',
      'Frigo basse consommation',
      'Eclairage LED',
      'Restauration durable',
      'Abris à vélos',
      'Récupérateur d’eau de pluie',
      'Plan d’adaptation au dérèglement climatique',
      'Pompe à chaleur',
      'Gestion des biodéchets',
      'Panneaux solaires',
      'Communication &amp; labélisation',
      'Chauffe-eau solaire',
      'Lutte contre le gaspillage alimentaire',
      'Serres agricoles',
      'Rétrofit électrique',
      'Chauffage au bois',
      'Plan de transition bas carbone',
      'Stratégie RSE',
      'Numérique responsable',
      'Projet de recherche',
      'Réseau de chaleur',
      'Chaleur de récupération',
      'Géothermie',
      'Energie hydraulique'
    ]
  },
  {
    id: 3,
    url: 'questionnaire/resultat?siret=82141193100016&effectif=ME&locaux=proprietaire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=oui&audit=oui&selection-audit=consommation-energie&selection-audit=eau&selection-audit=performance-energetique&selection-audit=bilan-carbone&selection-audit=certification&selection-audit=matieres-premieres&selection-audit=dechets#questionnaire-resultat',
    values: [
      'Diagnostic à 360° sur la transition écologique',
      'Sensibilisation des équipes',
      'Plan d’action économies d’énergie',
      "Plan d'action mobilité",
      'Plan d’action eau',
      'Plan d’action déchets &amp; pertes matière',
      'Réduction des emballages',
      'Bilan de gaz à effet de serre',
      'Économiseurs d’eau pour les sanitaires',
      "Économies d'eau en extérieur",
      'Ouvrants et ombrages',
      'Composteur',
      'Maîtrise des besoins de chauffage',
      'Audit énergétique',
      'Acquisition de vélos',
      'Isolation thermique',
      'Éco-conception d’un produit ou service',
      'Formation environnement',
      'Recrutement',
      'Tri des déchets',
      "Acquisition d'un véhicule propre",
      'Sèche-linge basse consommation',
      'Frigo basse consommation',
      'Eclairage LED',
      'Restauration durable',
      'Abris à vélos',
      'Récupérateur d’eau de pluie',
      'Plan d’adaptation au dérèglement climatique',
      'Pompe à chaleur',
      'Gestion des biodéchets',
      'Panneaux solaires',
      'Communication &amp; labélisation',
      'Chauffe-eau solaire',
      'Lutte contre le gaspillage alimentaire',
      'Serres agricoles',
      'Rétrofit électrique',
      'Chauffage au bois',
      'Plan de transition bas carbone',
      'Stratégie RSE',
      'Numérique responsable',
      'Projet de recherche',
      'Réseau de chaleur',
      'Chaleur de récupération',
      'Géothermie',
      'Energie hydraulique',
      'Diagnostic à 360° sur la transition écologique',
      'Sensibilisation des équipes',
      'Plan d’action économies d’énergie',
      "Plan d'action mobilité",
      'Plan d’action eau',
      'Plan d’action déchets &amp; pertes matière',
      'Réduction des emballages',
      'Bilan de gaz à effet de serre',
      'Économiseurs d’eau pour les sanitaires',
      "Économies d'eau en extérieur",
      'Ouvrants et ombrages',
      'Composteur',
      'Maîtrise des besoins de chauffage',
      'Audit énergétique',
      'Acquisition de vélos',
      'Isolation thermique',
      'Éco-conception d’un produit ou service',
      'Formation environnement',
      'Recrutement',
      'Tri des déchets',
      "Acquisition d'un véhicule propre",
      'Sèche-linge basse consommation',
      'Frigo basse consommation',
      'Eclairage LED',
      'Restauration durable',
      'Abris à vélos',
      'Récupérateur d’eau de pluie',
      'Plan d’adaptation au dérèglement climatique',
      'Pompe à chaleur',
      'Gestion des biodéchets',
      'Panneaux solaires',
      'Communication &amp; labélisation',
      'Chauffe-eau solaire',
      'Lutte contre le gaspillage alimentaire',
      'Serres agricoles',
      'Rétrofit électrique',
      'Chauffage au bois',
      'Plan de transition bas carbone',
      'Stratégie RSE',
      'Numérique responsable',
      'Projet de recherche',
      'Réseau de chaleur',
      'Chaleur de récupération',
      'Géothermie',
      'Energie hydraulique'
    ]
  },
  {
    id: 4,
    url: 'questionnaire/resultat?siret=21490007800012&effectif=PE&locaux=proprietaire-et-locataire&mobilite=maximum&matieres-premieres=maximum&tri-dechets=oui&dechets=non&gestion-eau=non&energie=non&audit=non#questionnaire-resultat',
    values: [
      'Diagnostic à 360° sur la transition écologique',
      'Sensibilisation des équipes',
      'Bilan de gaz à effet de serre',
      'Ouvrants et ombrages',
      'Maîtrise des besoins de chauffage',
      'Audit énergétique',
      'Isolation thermique',
      'Formation environnement',
      'Recrutement',
      'Sèche-linge basse consommation',
      'Frigo basse consommation',
      'Plan d’adaptation au dérèglement climatique',
      'Communication &amp; labélisation',
      'Serres agricoles',
      'Plan de transition bas carbone',
      'Stratégie RSE',
      'Projet de recherche',
      'Diagnostic à 360° sur la transition écologique',
      'Sensibilisation des équipes',
      'Bilan de gaz à effet de serre',
      'Ouvrants et ombrages',
      'Maîtrise des besoins de chauffage',
      'Audit énergétique',
      'Isolation thermique',
      'Formation environnement',
      'Recrutement',
      'Sèche-linge basse consommation',
      'Frigo basse consommation',
      'Plan d’adaptation au dérèglement climatique',
      'Communication &amp; labélisation',
      'Serres agricoles',
      'Plan de transition bas carbone',
      'Stratégie RSE',
      'Projet de recherche'
    ]
  }
]
