/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Données de dispositifs, avec des informations générales, relatifs à l'aide proposée et des données d'éligibilité.
 */
export type Dispositif = {
  /**
   * Titre commercial du dispositif. Si pas de titre commercial clairement identifé, un titre générique du type "Dispositif { opérateur de contact }" peut être utilisé.
   */
  titre: string;
  /**
   * Titre du dispositif pour les metadatas de la page. Il s'agit du titre qui sera affiché dans l'onglet du navigateur.
   */
  metaTitre?: string;
  /**
   * TODO
   */
  promesse: string;
  /**
   * La description donne les principales informations du dispositif en quelques lignes
   */
  description?: string;
  /**
   * Description du dispositif pour les metadatas de la page. Il s'agit de la description qui sera affichée dans les résultats de recherche.
   */
  metaDescription?: string;
  /**
   * La description longue La description longue est facultative. Elle peut être ajoutée si on juge que l'utilisateur ne dispose pas des informations suffisantes avec les seules autres informations. Elle peut être ajoutée par exemple pour définir un terme technique, pour détailler une loi à laquelle un dispositif fait référence ou pour détailler les projets concernés par un financement
   */
  "description longue"?: string;
  /**
   * Premier jour de validité de l'offre. Date au format JJ/MM/AAAA
   */
  "début de validité"?: string;
  /**
   * Dernier jour de validité de l'offre. Date au format JJ/MM/AAAA
   */
  "fin de validité"?: string;
  /**
   * champ présent si le programme est temporairement désactivé
   */
  "aide temporairement indisponible"?: string;
  /**
   * TODO
   */
  url?: string;
  /**
   * TODO
   */
  illustration: string;
  /**
   * Objectifs intermédiaires à réaliser pour mettre en place le dispositif
   */
  objectifs: {
    /**
     * Explication de l'objectif intermédiaire à réaliser
     */
    description?: string;
    liens?: (
      | {
          /**
           * TODO
           */
          lien: string;
          /**
           * TODO
           */
          texte: string;
        }
      | {
          /**
           * TODO
           */
          formulaire: boolean;
        }
    )[];
    [k: string]: unknown;
  }[];
  /**
   * L'opérateur de contact est l'opérateur à contacter pour obtenir des informations supplémentaires sur le dispositif.
   */
  "opérateur de contact":
    | "ADEME"
    | "Agence de l'Eau Loire-Bretagne"
    | "Agence de l'Eau Rhône-Méditerranée-Corse"
    | "Agence de l'Eau"
    | "Banque Publique d'Investissement France"
    | "Breizh Fab"
    | "CCI Bretagne"
    | "CCI ou CMA"
    | "Chambre de Commerce et de l'Industrie"
    | "Centre Technique des Industries Mécaniques"
    | "Chambre des Métiers et de l'Artisanat"
    | "DDFIP"
    | "DREAL Bretagne"
    | "EcoCO2"
    | "France Rénov'"
    | "InvestEU"
    | "Ministère de la Transition Écologique"
    | "Confédération de l'Artisanat et des Petites Entreprises du Bâtiment"
    | "Région Bretagne"
    | "Région Grand Est"
    | "Saur"
    | "Suez"
    | "Union des industries et métiers de la métallurgie"
    | "Véolia Eau"
    | "Centre national d'enseignement à distance"
    | "Voies Navigables de France"
    | "Région Centre-Val de Loire"
    | "Région Occitanie"
    | "Région Hauts-de-France"
    | "Région Île-de-France"
    | "Région Normandie"
    | "Région Pays de la Loire"
    | "Région Sud (PACA)"
    | "Agence Régionale Biodiversité et Environnement"
    | "Office français de la biodiversité"
    | "Région Bourgogne-Franche-Comté"
    | "Région Auvergne-Rhône-Alpes"
    | "Région Nouvelle-Aquitaine"
    | "Agence de Développement Economique de Corse"
    | "Agence de Tourisme de la Corse"
    | "Région Guadeloupe"
    | "Avere-France"
    | "Opcommerce"
    | "Centre National du Livre"
    | "Banque de France"
    | "Constructys"
    | "Atlas"
    | "Opco AFDAS"
    | "Opco Ocapiat"
    | "Opco 2i"
    | "Opco EP"
    | "Opco Mobilités"
    | "Opco Santé"
    | "Opco Uniformation"
    | "ANACT";
  /**
   * Le contact en cas de question, peut être un lien vers le formulaire, un mail ou une url.
   */
  "contact question"?: string;
  /**
   * Les autres opérateurs peuvent être des opérateurs co-financeurs, ou des partenaires du dispositif. Ils doivent être différents de l'opérateur de contcat.
   */
  "autres opérateurs"?: Operators[];
  /**
   * Précise s'il s'agit d'une aide financière, d'une étude, ou d'un prêt.
   */
  "nature de l'aide": "étude" | "formation" | "financement" | "avantage fiscal" | "prêt";
  /**
   * Précise s'il s'agit d'un dispositif en autonomie ou s'il y aura des interactions avec l'opérateur.
   */
  "activable en autonomie"?: string;
  /**
   * Uniquement pour les accompagnements. Ce champ est utile et requis uniquement si l'aide est de nature "accompagnement". Elle précise le coût reste à charge de l'utilisateur pour bénéficier de l'accompagnement. Il s'agit d'un champ texte, à des fins d'affichage.
   */
  "coût de l'accompagnement"?: string;
  /**
   * Uniquement pour les accompagnements. Nombre de jours d'accompagnement du prestataire, suivi de l'étalement de son intervention le cas échéant. Par exemple : "12 jours de prestation répartis sur 6 à 8 mois"
   */
  "durée de l'accompagnement"?: string;
  /**
   * Ce champ est utile et requis uniquement si l'aide est de nature "financement". Elle précise le montant du financement, de préférence en €, à défaut en %. Il s'agit d'un champ texte, à des fins d'affichage.
   */
  "montant du financement"?: string;
  /**
   * Ce champ est utile et requis uniquement si l'aide est de nature "avantage fiscal". Elle précise le montant de l'avantage fiscal, en %. Il s'agit d'un champ texte, à des fins d'affichage.
   */
  "montant de l'avantage fiscal"?: string;
  /**
   * Ce champ est utile et requis uniquement si l'aide est de nature "prêt". Il s'agit d'un champ texte, à des fins d'affichage.
   */
  "montant du prêt"?: string;
  /**
   * Ce champ est utile et requis uniquement si l'aide est de nature "prêt". Il s'agit d'un champ texte, à des fins d'affichage.
   */
  "durée du prêt"?: string;
  /**
   * Les conditions d'éligibilité, écrites en langage naturel, pour affichage sur la fiche de résultat
   */
  "conditions d'éligibilité": {
    /**
     * @minItems 1
     */
    "secteur d'activité": [string, ...string[]];
    /**
     * @minItems 1
     */
    "secteur géographique": [string, ...string[]];
    /**
     * @minItems 2
     */
    "taille de l'entreprise": [string, string, ...string[]];
    /**
     * @minItems 1
     */
    "nombre d'années d'activité": [string, ...string[]];
    /**
     * @minItems 1
     */
    "autres critères d'éligibilité"?: [string, ...string[]];
    [k: string]: unknown;
  };
  /**
   * Données d'éligibilite du programme. Sous format codifié pour traitements automatiques
   */
  eligibilityData?: {
    [k: string]: unknown;
  };
  /**
   * Mécanismes publicodes (https://publi.codes/) associés au dispositif. Doit être en langage publicodes valide. Les données nécessaires à l'évaluation des règles (contrat d'interface) sont matérialisés par des clés sans valeurs.
   */
  publicodes: {
    /**
     * Mécanisme pour évaluer si un dispositif doit être affiché à un utilisateur ou non. Est souvent plus restrictive que les mécanismes d'éligibilité
     */
    "entreprise . est ciblée":
      | {
          [k: string]: unknown;
        }
      | string;
    /**
     * Le nombre d'objectifs prioritaires auquel répond le dispositif.
     */
    "entreprise . a un objectif ciblé"?: {
      "une de ces conditions"?: string[];
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Certains programmes ont des caractéristiques différentes en fonction de différents paramètres tel que la région ou le domaine d'activité. Ces champs conditionnels permettent de gérer ces modifications par rapport au cas le plus commun.
   */
  "champs conditionnels"?: {
    "une de ces conditions"?: string[];
    "toutes ces conditions"?: string[];
    [k: string]: unknown;
  }[];
} & (
  | {
      "nature de l'aide"?: "formation";
      [k: string]: unknown;
    }
  | {
      "nature de l'aide"?: "financement";
      [k: string]: unknown;
    }
  | {
      "nature de l'aide"?: "avantage fiscal";
      [k: string]: unknown;
    }
  | {
      "nature de l'aide"?: "prêt";
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }
);
export type Operators =
  | "ADEME"
  | "Agence de l'Eau Loire-Bretagne"
  | "Agence de l'Eau Rhône-Méditerranée-Corse"
  | "Agence de l'Eau"
  | "Banque Publique d'Investissement France"
  | "Breizh Fab"
  | "CCI Bretagne"
  | "CCI ou CMA"
  | "Chambre de Commerce et de l'Industrie"
  | "Centre Technique des Industries Mécaniques"
  | "Chambre des Métiers et de l'Artisanat"
  | "DDFIP"
  | "DREAL Bretagne"
  | "EcoCO2"
  | "France Rénov'"
  | "InvestEU"
  | "Ministère de la Transition Écologique"
  | "Confédération de l'Artisanat et des Petites Entreprises du Bâtiment"
  | "Région Bretagne"
  | "Région Grand Est"
  | "Saur"
  | "Suez"
  | "Union des industries et métiers de la métallurgie"
  | "Véolia Eau"
  | "Centre national d'enseignement à distance"
  | "Voies Navigables de France"
  | "Région Centre-Val de Loire"
  | "Région Occitanie"
  | "Région Hauts-de-France"
  | "Région Île-de-France"
  | "Région Normandie"
  | "Région Pays de la Loire"
  | "Région Sud (PACA)"
  | "Agence Régionale Biodiversité et Environnement"
  | "Office français de la biodiversité"
  | "Région Bourgogne-Franche-Comté"
  | "Région Auvergne-Rhône-Alpes"
  | "Région Nouvelle-Aquitaine"
  | "Agence de Développement Economique de Corse"
  | "Agence de Tourisme de la Corse"
  | "Région Guadeloupe"
  | "Avere-France"
  | "Opcommerce"
  | "Centre National du Livre"
  | "Banque de France"
  | "Constructys"
  | "Atlas"
  | "Opco AFDAS"
  | "Opco Ocapiat"
  | "Opco 2i"
  | "Opco EP"
  | "Opco Mobilités"
  | "Opco Santé"
  | "Opco Uniformation"
  | "ANACT";
