import { SearchResultsDataType } from '../resultDataType'

export const tests: SearchResultsDataType = [
  {
    id: 0,
    url: 'aides-entreprise',
    count: 120,
    values: []
  },
  {
    id: 1,
    url: 'questionnaire/resultat?siret=83014132100042&effectif=TPE&locaux=proprietaire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=non&audit=non#questionnaire-resultat',
    values: [
      'Communauté du Coq Vert',
      'Entreprises engagées pour la nature',
      'Formation ADEME',
      'Performa Environnement',
      'Diagnostic SARE',
      'TPE gagnantes sur tous les coûts',
      'Diagnostic Transition Ecologique',
      'Formations Transition Écologique et Énergétique',
      'Programme Volontaire Français ACT',
      'Diag Ecoconception',
      'Étude "Économie de la fonctionnalité"',
      'Étude "Éco-conception"',
      'Étude "projet de recherche"',
      'Étude "réemploi réutilisation réparation"',
      'Mission de Conseil RSE',
      'Mission Stratégie Environnement',
      'Aides au réemploi des emballages',
      'Bonus écologique',
      'Coup de pouce Chauffage',
      'Investissement "Ecoconception"',
      'Investissement "VTE Vert"',
      'Prime à la conversion',
      'Rétrofit électrique',
      'Sobriété et Résilience des Territoires',
      'Tremplin',
      'Prêt Action Climat',
      'Prêt Vert - Ademe',
      'Prêt Vert',
      'Flotte de vélos à disposition',
      "Crédit d'Impôt Rénovation Énergétique (CIRE)"
    ]
  },
  {
    id: 2,
    url: 'questionnaire/resultat/projet/sensibilisation-equipes?siret=83014132100042&effectif=TPE&locaux=proprietaire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=non&audit=non',
    values: ['Formation ADEME']
  },
  {
    id: 3,
    url: 'questionnaire/resultat?siret=78893947800020&locaux=locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=oui&dechets=oui&gestion-eau=oui&energie=oui&audit=non#questionnaire-resultat',
    values: [
      'Baisse Les Watts',
      'Communauté du Coq Vert',
      'Entreprises engagées pour la nature',
      'Formation ADEME',
      'Performa Environnement',
      'TPE gagnantes sur tous les coûts',
      'Diagnostic Transition Ecologique',
      'Formations Transition Écologique et Énergétique',
      'Visite Énergie CCI',
      'Accélérateur décarbonation',
      'Programme Volontaire Français ACT',
      'Booster Éco-Énergie Tertiaire',
      'Diag Ecoconception',
      'Diagnostic RSE',
      'Étude "Économie de la fonctionnalité"',
      'Étude "Éco-conception"',
      'Étude "projet de recherche"',
      'Étude "réemploi réutilisation réparation"',
      'Étude "Solaire thermique"',
      'Étude "Test géothermie"',
      'Mission de Conseil RSE',
      'Mission Stratégie Environnement',
      'Aides au réemploi des emballages',
      'Bonus écologique',
      'Coup de pouce Chauffage',
      'Investissement "Boucle d’eau géothermique"',
      'Investissement "Chaleur bois"',
      'Investissement "Contrat Chaleur Renouvelable"',
      'Investissement "Ecoconception"',
      'Investissement "Géothermie de surface et d\'aérothermie"',
      'Investissement "Géothermie profonde"',
      'Investissement "PAC solaire"',
      'Investissement "Solaire thermique"',
      'Investissement "Systèmes Solaires Combinés"',
      'Investissement "VTE Vert"',
      'Prime à la conversion',
      'Rétrofit électrique',
      'Sobriété et Résilience des Territoires',
      'Tremplin',
      'Prêt Action Climat',
      'Prêt Vert - Ademe',
      'Prêt Vert',
      'Flotte de vélos à disposition'
    ]
  },
  {
    id: 4,
    url: 'questionnaire/resultat?siret=82141193100016&effectif=ME&locaux=proprietaire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=oui&audit=oui&selection-audit=consommation-energie&selection-audit=eau&selection-audit=performance-energetique&selection-audit=bilan-carbone&selection-audit=certification&selection-audit=matieres-premieres&selection-audit=dechets#questionnaire-resultat',
    values: [
      'Baisse Les Watts',
      'Charte "zéro déchet plastique"',
      'Entreprises engagées pour la nature',
      'Formation ADEME',
      'Diagnostic SARE',
      'Visite Énergie CMA',
      'Formations Transition Écologique et Énergétique',
      'Visite Énergie CCI',
      'CEDRE Premier Pas',
      'Diag Ecoconception',
      "Diag Perf'Immo",
      'Diagnostic RSE',
      'Formation écogestes',
      'Étude "Économie de la fonctionnalité"',
      'Étude "projet de recherche"',
      'Étude "Solaire thermique"',
      'Étude "Test géothermie"',
      'Formations du CFDE',
      'Fresque de la Mobilité',
      'Mission Stratégie Environnement',
      'Aides au réemploi des emballages',
      'Bonus écologique',
      'CEDRE Investissement',
      'Chèque Transition Bioéthanol',
      'Coup de pouce Chauffage',
      'Investissement "Boucle d’eau géothermique"',
      'Investissement "Chaleur bois"',
      'Investissement "Contrat Chaleur Renouvelable"',
      'Investissement "Géothermie de surface et d\'aérothermie"',
      'Investissement "Géothermie profonde"',
      'Investissement "PAC solaire"',
      'Investissement "Solaire thermique"',
      'Investissement "Systèmes Solaires Combinés"',
      'Investissement "VTE Vert"',
      'Nature ta ville',
      'Prime à la conversion',
      'Rétrofit électrique',
      'Plan Solaire Smart PV',
      'Plan Solaire Ready',
      'Tremplin',
      'Prêt Vert - Ademe',
      'Prêt Vert',
      'Sud Prêt Climat',
      'Flotte de vélos à disposition',
      'Mécénaturel',
      "Crédit d'Impôt Rénovation Énergétique (CIRE)"
    ]
  },
  {
    id: 5,
    url: 'questionnaire/resultat?siret=21490007800012&effectif=PE&locaux=proprietaire-et-locataire&mobilite=maximum&matieres-premieres=maximum&tri-dechets=oui&dechets=non&gestion-eau=non&energie=non&audit=non#questionnaire-resultat',
    values: [
      'Entreprises engagées pour la nature',
      'Formation ADEME',
      'Formations Transition Écologique et Énergétique',
      'Programme Volontaire Français ACT',
      'Enviroveille',
      'Formations du CFDE',
      'Mission Stratégie Environnement',
      'Investissement "VTE Vert"',
      'Sobriété et Résilience des Territoires',
      'Prêt Action Climat',
      'Prêt Vert - Ademe',
      'Prêt Vert'
    ]
  }
]
