import { SearchResultsDataType } from '../resultDataType'

export const tests: SearchResultsDataType = [
  {
    id: 0,
    url: 'aides-entreprise',
    count: 120,
    values: []
  },
  {
    id: 1,
    url: 'questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=83014132100034&effectif=TPE&locaux=proprietaire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=non&audit=non#questionnaire-resultat',
    values: [
      'Communauté du Coq Vert',
      'Entreprises engagées pour la nature',
      'Formation ADEME',
      'Performa Environnement',
      'Diagnostic SARE',
      'TPE gagnantes sur tous les coûts',
      'Diagnostic Transition Ecologique',
      'Formations Transition Écologique et Énergétique',
      'Programme Volontaire Français ACT',
      'Diag Ecoconception',
      'Étude "Économie de la fonctionnalité"',
      'Étude "Éco-conception"',
      'Étude "réemploi réutilisation réparation"',
      'Mission de Conseil RSE',
      'Mission Stratégie Environnement',
      'Aides au réemploi des emballages',
      'Bonus écologique',
      'Coup de pouce Chauffage',
      'Investissement "Ecoconception"',
      'Investissement "VTE Vert"',
      'Prime à la conversion',
      'Rétrofit électrique',
      'Sobriété et Résilience des Territoires',
      'Tremplin',
      'Prêt Action Climat',
      'Prêt Vert',
      'Flotte de vélos à disposition',
      "Crédit d'Impôt Rénovation Énergétique (CIRE)"
    ]
  },
  {
    id: 2,
    url: 'questionnaire/resultat/projet/isolation-thermique?choix-du-parcours=j-ai-un-projet&siret=83014132100034&effectif=TPE&objectifs=building',
    values: ['Diagnostic SARE', 'Prêt Économies d’Énergie (PEE)', 'Prêt Vert', "Crédit d'Impôt Rénovation Énergétique (CIRE)"]
  },
  {
    id: 3,
    url: 'questionnaire/resultat/projet/sensibilisation-equipes?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=83014132100034&effectif=TPE&locaux=proprietaire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=non&audit=non',
    values: ['Formation ADEME']
  },
  {
    id: 4,
    url: 'questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=78893947800020&locaux=locataire&mobilite=oui&matieres-premieres=oui&tri-dechets=oui&dechets=oui&gestion-eau=oui&energie=oui&audit=non#questionnaire-resultat',
    values: [
      'Baisse Les Watts',
      'Communauté du Coq Vert',
      'Entreprises engagées pour la nature',
      'Formation ADEME',
      'Performa Environnement',
      'Diagnostic SARE',
      'TPE gagnantes sur tous les coûts',
      'Diagnostic Transition Ecologique',
      'Formations Transition Écologique et Énergétique',
      'Visite Énergie CCI',
      'Accélérateur décarbonation',
      'Programme Volontaire Français ACT',
      'Diag Ecoconception',
      'Diagnostic RSE',
      'Étude "Économie de la fonctionnalité"',
      'Étude "Éco-conception"',
      'Étude "réemploi réutilisation réparation"',
      'Étude "Solaire thermique"',
      'Mission de Conseil RSE',
      'Mission Stratégie Environnement',
      'Aides au réemploi des emballages',
      'Bonus écologique',
      'Coup de pouce Chauffage',
      'Investissement "Ecoconception"',
      'Investissement "VTE Vert"',
      'Prime à la conversion',
      'Rétrofit électrique',
      'Sobriété et Résilience des Territoires',
      'Tremplin',
      'Prêt Action Climat',
      'Prêt Vert',
      'Flotte de vélos à disposition',
      "Crédit d'Impôt Rénovation Énergétique (CIRE)"
    ]
  },
  {
    id: 5,
    url: 'questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=82141193100016&effectif=ME&locaux=proprietaire&mobilite=oui&matieres-premieres=oui&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=oui&audit=oui&selection-audit=consommation-energie&selection-audit=eau&selection-audit=performance-energetique&selection-audit=bilan-carbone&selection-audit=certification&selection-audit=matieres-premieres&selection-audit=dechets#questionnaire-resultat',
    values: [
      'Baisse Les Watts',
      'Charte "zéro déchet plastique"',
      'Entreprises engagées pour la nature',
      'Formation ADEME',
      'Diagnostic SARE',
      'Visite Énergie CMA',
      'Formations Transition Écologique et Énergétique',
      'Visite Énergie CCI',
      'CEDRE Premier Pas',
      'Diag Ecoconception',
      "Diag Perf'Immo",
      'Diagnostic RSE',
      'Formation écogestes',
      'Étude "Économie de la fonctionnalité"',
      'Étude "Solaire thermique"',
      'Formations du CFDE',
      'Fresque de la Mobilité',
      'Mission Stratégie Environnement',
      'Aides au réemploi des emballages',
      'Bonus écologique',
      'CEDRE Investissement',
      'Chèque Transition Bioéthanol',
      'Coup de pouce Chauffage',
      'Investissement "Chaleur bois"',
      'Investissement "VTE Vert"',
      'Nature ta ville',
      'Prime à la conversion',
      'Rétrofit électrique',
      'Plan Solaire Smart PV',
      'Plan Solaire Ready',
      'Tremplin',
      'Prêt Vert',
      'Sud Prêt Climat',
      'Flotte de vélos à disposition',
      'Mécénaturel',
      "Crédit d'Impôt Rénovation Énergétique (CIRE)"
    ]
  },
  {
    id: 6,
    url: 'questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=21490007800012&effectif=PE&locaux=proprietaire-et-locataire&mobilite=maximum&matieres-premieres=maximum&tri-dechets=oui&dechets=non&gestion-eau=non&energie=non&audit=non#questionnaire-resultat',
    values: [
      'Entreprises engagées pour la nature',
      'Formation ADEME',
      'Formations Transition Écologique et Énergétique',
      'Programme Volontaire Français ACT',
      'Formations du CFDE',
      'Mission Stratégie Environnement',
      'Investissement "VTE Vert"',
      'Sobriété et Résilience des Territoires',
      'Prêt Action Climat',
      'Prêt Vert'
    ]
  }
]
