SECTOR_COLUMN_MAP = {
    "AAgriculture, sylviculture et pêche": "A",
    "BIndustries extractives": "B",
    "CIndustrie manufacturière": "C",
    "DProduction et distribution d'électricité, de gaz, de vapeur et d'air conditionné": "D",
    "EProduction et distribution d'eau, assainissement, gestion des déchets et dépollution": "E",
    "FConstruction": "F",
    "GCommerce, réparation d'automobiles et de motocycles": "G",
    "HTransports et entreposage": "H",
    "IHébergement et restauration": "I",
    "JInformation et communication": "J",
    "KActivités financières et d'assurance": "K",
    "LActivités immobilières": "L",
    "MActivités spécialisées, scientifiques et techniques": "M",
    "NActivités de services administratifs et de soutien": "N",
    "OAdministration publique": "O",
    "PEnseignement": "P",
    "QSanté humaine et action sociale": "Q",
    "RArts, spectacles et activités récréatives": "R",
    "SAutres activités de services": "S",
    "TActivités des ménages en tant qu'employeurs, activités indifférenciées des ménages en tant que producteurs de biens et services pour usage propre": "T",
    "UActivités extra-territoriales": "U",
}

COG_MAPPING = {
    "France": "PAYS-99100",
    "Guadeloupe": "REG-01",
    "Martinique": "REG-02",
    "Guyane": "REG-03",
    "La Réunion": "REG-04",
    "Mayotte": "REG-06",
    "Île-de-France": "REG-11",
    "Centre-Val de Loire": "REG-24",
    "Bourgogne-Franche-Comté": "REG-27",
    "Normandie": "REG-28",
    "Hauts-de-France": "REG-32",
    "Grand Est": "REG-44",
    "Pays de la Loire": "REG-52",
    "Bretagne": "REG-53",
    "Nouvelle-Aquitaine": "REG-75",
    "Occitanie": "REG-76",
    "Auvergne-Rhône-Alpes": "REG-84",
    "Provence-Alpes-Côte d'Azur": "REG-93",
    "Corse": "REG-94",
    "Alpes-de-Haute-Provence": "DEP-04",
    "Hautes-Alpes": "DEP-05",
    "Alpes-Maritimes": "DEP-06",
    "Bouches-du-Rhône": "DEP-13",
    "Var": "DEP-83",
    "Vaucluse": "DEP-84",
    "Eure-et-Loir": "DEP-28",
    "Loiret": "DEP-45",
    "Landes": "DEP-40",
    "Seine-et-Marne": "DEP-77",
    "Jura": "DEP-39",
    "Saint-Martin": "DEP-978",
    "Nouvelle-Calédonie": "COM-988",
    "Polynésie française": "COM-987",
    "Saint-Barthélemy": "COM-977",
    "Saint-Pierre-Et-Miquelon": "COM-975",
}
