/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContactButton: typeof import('./components/contact/ContactButton.vue')['default']
    ContactHelp: typeof import('./components/contact/ContactHelp.vue')['default']
    ContactMail: typeof import('./components/contact/ContactMail.vue')['default']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrSelect: typeof import('@gouvminint/vue-dsfr')['DsfrSelect']
    ProgramAccordion: typeof import('./components/program/ProgramAccordion.vue')['default']
    ProgramCard: typeof import('./components/program/list/ProgramCard.vue')['default']
    ProgramDetail: typeof import('./components/program/detail/ProgramDetail.vue')['default']
    ProgramEligibility: typeof import('./components/program/ProgramEligibility.vue')['default']
    ProgramFilters: typeof import('./components/program/list/ProgramFilters.vue')['default']
    ProgramForm: typeof import('./components/program/detail/ProgramForm.vue')['default']
    ProgramList: typeof import('./components/program/list/ProgramList.vue')['default']
    ProgramListHeaderResult: typeof import('./components/program/list/ProgramListHeaderResult.vue')['default']
    ProgramListNoResults: typeof import('./components/program/list/ProgramListNoResults.vue')['default']
    ProgramLongDescription: typeof import('./components/program/ProgramLongDescription.vue')['default']
    ProgramObjective: typeof import('./components/program/ProgramObjective.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeeContact: typeof import('./components/home/TeeContact.vue')['default']
    TeeCredits: typeof import('./components/TeeCredits.vue')['default']
    TeeCta: typeof import('./components/home/TeeCta.vue')['default']
    TeeDsfrButton: typeof import('./components/button/TeeDsfrButton.vue')['default']
    TeeDsfrSearchBar: typeof import('./components/tracks/TeeDsfrSearchBar.vue')['default']
    TeeFooter: typeof import('./components/TeeFooter.vue')['default']
    TeeForm: typeof import('./components/TeeForm.vue')['default']
    TeeHeader: typeof import('./components/TeeHeader.vue')['default']
    TeeHomeInfos: typeof import('./components/home/TeeHomeInfos.vue')['default']
    TeeHomeSteps: typeof import('./components/home/TeeHomeSteps.vue')['default']
    TeeMatomo: typeof import('./components/TeeMatomo.vue')['default']
    TeeNoResults: typeof import('./components/results/TeeNoResults.vue')['default']
    TeeProgramDetail: typeof import('./components/program/TeeProgramDetail.vue')['default']
    TeeQuestionnaire: typeof import('./components/TeeQuestionnaire.vue')['default']
    TeeQuestionnaireResult: typeof import('./components/questionnaire/TeeQuestionnaireResult.vue')['default']
    TeeResults: typeof import('./components/results/TeeResults.vue')['default']
    TeeResultsFilter: typeof import('./components/results/TeeResultsFilter.vue')['default']
    TeeSidebar: typeof import('./components/TeeSidebar.vue')['default']
    TeeTile: typeof import('./components/TeeTile.vue')['default']
    TeeTrack: typeof import('./components/tracks/TeeTrack.vue')['default']
    TeeTrackButtonInput: typeof import('./components/tracks/TeeTrackButtonInput.vue')['default']
    TeeTrackInput: typeof import('./components/tracks/TeeTrackInput.vue')['default']
    TeeTrackSelect: typeof import('./components/tracks/TeeTrackSelect.vue')['default']
    VIcon: typeof import('oh-vue-icons')['OhVueIcon']
  }
}
