/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContactButton: typeof import('./components/contact/ContactButton.vue')['default']
    ContactHelp: typeof import('./components/contact/ContactHelp.vue')['default']
    ContactMail: typeof import('./components/contact/ContactMail.vue')['default']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    ProgramAccordion: typeof import('./components/program/detail/ProgramAccordion.vue')['default']
    ProgramCard: typeof import('./components/program/list/ProgramCard.vue')['default']
    ProgramDetail: typeof import('./components/program/detail/ProgramDetail.vue')['default']
    ProgramEligibility: typeof import('./components/program/detail/ProgramEligibility.vue')['default']
    ProgramFilters: typeof import('./components/program/list/ProgramFilters.vue')['default']
    ProgramForm: typeof import('./components/program/detail/ProgramForm.vue')['default']
    ProgramList: typeof import('./components/program/list/ProgramList.vue')['default']
    ProgramListHeaderResult: typeof import('./components/program/list/ProgramListHeaderResult.vue')['default']
    ProgramListNoResults: typeof import('./components/program/list/ProgramListNoResults.vue')['default']
    ProgramLongDescription: typeof import('./components/program/detail/ProgramLongDescription.vue')['default']
    ProgramObjective: typeof import('./components/program/detail/ProgramObjective.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeeContact: typeof import('./components/home/TeeContact.vue')['default']
    TeeCredits: typeof import('./components/TeeCredits.vue')['default']
    TeeCta: typeof import('./components/home/TeeCta.vue')['default']
    TeeDsfrButton: typeof import('./components/button/TeeDsfrButton.vue')['default']
    TeeFooter: typeof import('./components/TeeFooter.vue')['default']
    TeeHeader: typeof import('./components/TeeHeader.vue')['default']
    TeeHomeInfos: typeof import('./components/home/TeeHomeInfos.vue')['default']
    TeeHomeSteps: typeof import('./components/home/TeeHomeSteps.vue')['default']
    TeeMatomo: typeof import('./components/TeeMatomo.vue')['default']
    TeeQuestionnaire: typeof import('./components/questionnaire/TeeQuestionnaire.vue')['default']
    TeeQuestionnaireResult: typeof import('./components/questionnaire/TeeQuestionnaireResult.vue')['default']
    TeeTile: typeof import('./components/TeeTile.vue')['default']
    TeeTrackButtonInput: typeof import('./components/track/form/TeeTrackButtonInput.vue')['default']
    TeeTrackInput: typeof import('./components/track/form/TeeTrackInput.vue')['default']
    TeeTrackSelect: typeof import('./components/track/form/TeeTrackSelect.vue')['default']
    TrackButton: typeof import('./components/track/form/TrackButton.vue')['default']
    TrackButtonInput: typeof import('./components/track/form/TrackButtonInput.vue')['default']
    TrackCallout: typeof import('./components/track/detail/TrackCallout.vue')['default']
    TrackCard: typeof import('./components/track/form/TrackCard.vue')['default']
    TrackCards: typeof import('./components/track/form/TrackCards.vue')['default']
    TrackContent: typeof import('./components/track/TrackContent.vue')['default']
    TrackHint: typeof import('./components/track/detail/TrackHint.vue')['default']
    TrackInfo: typeof import('./components/track/detail/TrackInfo.vue')['default']
    TrackInput: typeof import('./components/track/form/TrackInput.vue')['default']
    TrackLabel: typeof import('./components/track/detail/TrackLabel.vue')['default']
    TrackResume: typeof import('./components/track/detail/TrackResume.vue')['default']
    TrackSelect: typeof import('./components/track/form/TrackSelect.vue')['default']
    TrackSidebar: typeof import('./components/track/TrackSidebar.vue')['default']
    TrackSimpleButton: typeof import('./components/track/form/TrackSimpleButton.vue')['default']
    TrackSubmitButton: typeof import('./components/track/form/TrackSubmitButton.vue')['default']
    VIcon: typeof import('oh-vue-icons')['OhVueIcon']
  }
}
