export enum RouteName {
  Homepage = 'homepage',
  CatalogPrograms = 'catalogPrograms',
  CatalogProjects = 'catalogProjects',
  CatalogProgramDetail = 'catalog-program-detail',
  CatalogProjectDetail = 'catalog-project-detail',
  CatalogProjectFromProgramDetail = 'catalog-project-from-program-detail',
  AddProgram = 'add-program',
  ChatAdvisor = 'chat-advisor',
  Legal = 'legal',
  PersonalData = 'personal-data',
  QuestionnaireStart = 'questionnaire-start',
  Questionnaire = 'questionnaire',
  QuestionnaireResult = 'questionnaire-resultat',
  QuestionnaireResultDetail = 'questionnaire-result-detail',
  ProgramFromProjectDetail = 'program-from-project-detail',
  ProjectFromProgramDetail = 'project-from-program-detail',
  ProjectResultDetail = 'questionnaire-project-result-detail',
  Statistiques = 'statistics'
}
