class TableName:
    EXTERNAL_LINK_CLICKED_EVENTS = "external_link_clicked_events"
    DAILY_WEB_STATS = "daily_web_stats"
    OPPORTUNITIES = "opportunities"
    DETAIL_PAGE_VIEW = "detail_page_view"
    WEB_REGISTERED_SIRET = "web_registered_siret"
    COMPANIES = "companies"
    SIRET_SEARCH_ERROR = "siret_search_error"
    PROJECTS="projects"
    PROGRAMS="programs"

class CompaniesColumn:
    SIRET = "siret"
    NAF_SECTION = "naf_section"
    NAF_DIVISION = "naf_division"
    NAF_GROUP = "naf_group"
    NAF_CLASS = "naf_class"
    NAF_CODE = "naf_code"
    CITY_CODE = "city_code"
    DEPARTMENT = "department"
    REGION = "region"
    WORKFORCE_CATEGORY = "workforce_category"
    WORKFORCE_MIN = "workforce_min"
    WORKFORCE_MAX = "workforce_max"
