name: Compare Filtered Results

on:
  pull_request:

jobs:
  compare-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Run tests on main branch
        run: |
          npm install
          RESULTS_FILE=results_main.json npx playwright test filterResults.test.ts
        env:
          CI: true

      - name: Checkout feature branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run tests on feature branch
        run: |
          RESULTS_FILE=results_feature.json npx playwright test filterResults.test.ts
        env:
          CI: true

      - name: Compare results
        run: |
          npm install -g ts-node
          ts-node compareResults.ts
