name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ '22.x' ]
        project: ['chromium', 'firefox', 'Mobile Chrome']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm clean-install --foreground-scripts
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Build application
      env:
        VITE_DATA_TEST: true
        THIRD_PARTY_API_ENABLED: false
      run: npm run build
    - name: Run Playwright tests
      env:
        VITE_DATA_TEST: true
        THIRD_PARTY_API_ENABLED: false
      run: npx nx run @tee/nuxt-e2e:e2e -- --project="${{ matrix.project }}"
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.project }}
        path: playwright-report/
        retention-days: 30
