name: Visit StatPage 4 Times Daily to improve loading times

on:
  schedule:
    - cron: "25 1 * * *"
    - cron: "25 7 * * *"
    - cron: "25 13 * * *"
    - cron: "25 19 * * *"

jobs:
  visit-webpage:
    runs-on: ubuntu-latest

    steps:
      - name: Visit the webpage
        run: |
          curl -s -o /dev/null https://mission-transition-ecologique.beta.gouv.fr/stats
